Update Run Python Script.yml

diff --git a/.github/workflows/Run Python Script.yml b/.github/workflows/Run Python Script.yml
--- a/.github/workflows/Run Python Script.yml
+++ b/.github/workflows/Run Python Script.yml
@@ -1,7 +1,11 @@
-name: Run Python Script 1.3
+name: Run Python Script 1.5
 
 on:
   workflow_dispatch:
+    inputs:
+      user_input:
+        description: Input to be passed to the Python script
+        required: true
 
 jobs:
   run:
@@ -27,8 +31,19 @@ jobs:
       - name: Install Python dependencies
         run: |
           pip install -r ./requirements.txt
+          if [ $? -ne 0 ]; then
+            echo "Failed to install Python dependencies"
+            exit 1
+          fi
+
+      - name: Set user input as an environment variable
+        run: echo "USER_INPUT=${{ inputs.user_input }}" >> $GITHUB_ENV
 
       - name: Run Python script
         run: |
           choice=${USER_INPUT}
-          python main.py
+          python main.py "${choice}"
+          if [ $? -ne 0 ]; then
+            echo "Python script failed"
+            exit 1
+          fi
